### ISSUE TITLE
Cannot redirect

### ISSUE THREAD

**Issue by unnikked** [SocialiteProviders/Reddit#2]
I followed your instruction [here](http://socialiteproviders.github.io/providers/reddit/) and followed the [doc](http://laravel.com/docs/5.2/authentication#social-authentication) to play around. 

Of course I've created the app id and token on reddit. 

This is `AuthController.php`

```php
// namespace and imports here

class AuthController extends Controller
{
    public function redirectToProvider()
    {
        return Socialite::driver('reddit')->redirect();
    }

    public function handleProviderCallback()
    {
        $user = Socialite::driver('reddit')->user();
    }
}
```

And this is the `route.php` file:

```php
Route::get('auth/', 'Auth\AuthController@redirectToProvider');
Route::get('redirect/', 'Auth\AuthController@handleProviderCallback');
```

But when I hit `auth` I get this:

```
[2015-12-22 14:50:18] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function set() on a non-object' in /home/ubuntu/workspace/vendor/laravel/socialite/src/Two/AbstractProvider.php:134
Stack trace:
#0 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(133): Symfony\Component\Debug\Exception\FatalErrorException->__construct()
#1 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError()
#2 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(0): Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 /home/ubuntu/workspace/app/Http/Controllers/Auth/AuthController.php(81): Laravel\Socialite\Two\AbstractProvider->redirect()
#4 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(76): App\Http\Controllers\Auth\AuthController->redirectToProvider()
#5 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(76): call_user_func_array:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:76}()
#6 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction()
#7 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call()
#8 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()
#9 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}()
#10 /home/ubuntu/workspace/app/Http/Middleware/RedirectIfAuthenticated.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): App\Http\Middleware\RedirectIfAuthenticated->handle()
#12 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#13 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30}()
#15 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#16 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}()
#17 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then()
#18 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack()
#19 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch()
#20 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController()
#21 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Route->run()
#22 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#23 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}()
#24 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}()
#26 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(705): Illuminate\Pipeline\Pipeline->then()
#27 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(678): Illuminate\Routing\Router->runRouteWithinStack()
#28 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Routing/Router.php(654): Illuminate\Routing\Router->dispatchToRoute()
#29 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch()
#30 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#31 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139}()
#32 /home/ubuntu/workspace/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Barryvdh\Debugbar\Middleware\Debugbar->handle()
#34 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#35 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#37 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124}()
#38 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func:{/home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103}()
#40 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then()
#41 /home/ubuntu/workspace/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#42 /home/ubuntu/workspace/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle()
#43 /home/ubuntu/workspace/public/index.php(0): {main}()
#44 {main}  
```

It looks like it does not view any session. 

Any input is very appreciated. I'm using `Laravel 5.2`.

**Comment by unnikked** [comment]
Tried with the latest version of Laravel 5.1 LTS and it works, there is something wrong for Laravel 5.2

Unfortunately I do not know well Laravel in order to provide a pull request.

**Comment by brnlbs** [comment]
This seems like an issue with Laravel Socialite and Laravel 5.2 itself but I don't have an enviroment at the moment to look at this.

**Comment by AndyWendt** [comment]
@unnikked Try it now since I updated the manager package

**Comment by AndyWendt** [comment]
Most likely fixed with manager package update

**Comment by unnikked** [comment]
Sorry to being late. I've reproduced the scenario. Same steps of the original request. I'm sure I did everything the same way since I've documented the process thoroughly but now I get

Stack trace:

```
0. in Manager.php line 90
0. at Manager->createDriver('reddit') in Manager.php line 63
0. at Manager->driver('reddit') in SocialiteManager.php line 22
0. at SocialiteManager->with('reddit') in Facade.php line 218
0. at Facade::__callStatic('with', array('reddit')) in AuthController.php line 16
0. at Socialite::with('reddit') in AuthController.php line 16
0. at AuthController->redirectToProvider()
0. at call_user_func_array(array(object(AuthController), 'redirectToProvider'), array()) in Controller.php line 76
0. at Controller->callAction('redirectToProvider', array()) in ControllerDispatcher.php line 146
0. at ControllerDispatcher->call(object(AuthController), object(Route), 'redirectToProvider') in ControllerDispatcher.php line 94
0. at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
0. at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
0. at Pipeline->Illuminate\Routing\{closure}(object(Request))
0. at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
0. at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 96
0. at ControllerDispatcher->callWithinStack(object(AuthController), object(Route), object(Request), 'redirectToProvider') in ControllerDispatcher.php line 54
0. at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\Auth\AuthController', 'redirectToProvider') in Route.php line 174
0. at Route->runController(object(Request)) in Route.php line 140
0. at Route->run(object(Request)) in Router.php line 703
0. at Router->Illuminate\Routing\{closure}(object(Request))
0. at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
0. at Pipeline->Illuminate\Routing\{closure}(object(Request))
0. at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
0. at Pipeline->then(object(Closure)) in Router.php line 705
0. at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 678
0. at Router->dispatchToRoute(object(Request)) in Router.php line 654
0. at Router->dispatch(object(Request)) in Kernel.php line 246
0. at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
0. at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
0. at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
0. at CheckForMaintenanceMode->handle(object(Request), object(Closure))
0. at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), 0. object(Closure))) in Pipeline.php line 124
0. at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
0. at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
0. at Pipeline->Illuminate\Routing\{closure}(object(Request))
0. at call_user_func(object(Closure), object(Request)) in Pipeline.php line 103
0. at Pipeline->then(object(Closure)) in Kernel.php line 132
0. at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
0. at Kernel->handle(object(Request)) in index.php line 54
``` 

![schermata del 2016-01-20 11 13 27](https://cloud.githubusercontent.com/assets/2611548/12445869/1f804850-bf67-11e5-8c25-3a1548080c84.png)

**Comment by DraperStudio** [comment]
Andy did an update to the manager packages which seems to have broken several providers. I will try to look into it soon.

ping @AndyWendt

**Comment by AndyWendt** [comment]
@unnikked Thanks for sending the full debug log.  @DraperStudio I will look into this shortly

**Comment by AndyWendt** [comment]
Sounds like this might be a change in laravel 5.2

**Comment by AndyWendt** [comment]
@unnikked @DraperStudio 

The 5.2 issue is because, [I just found out](http://stackoverflow.com/questions/34529146/laravel-5-2-login-session-not-persisting), you need to wrap your routes now in a `Route::group`.  I didn't notice this until I started digging around.  And also a [reference in the docs](https://laravel.com/docs/5.2/routing#basic-routing)

```php
Route::group(['middleware' => ['web']], function () {
    \Route::get('auths', function() {
        return \Socialite::driver('reddit')->redirect();
    });

    \Route::get('/callback', function () {
        $user = \Socialite::driver('reddit')->user();

        dd($user);
    });
});
```

**Comment by DraperStudio** [comment]
@AndyWendt Good to finally know whats causing this.

**Comment by unnikked** [comment]
@AndyWendt :+1:
